aliyun-oss:
  endpoint: yourEndpoint
  access-key-id: yourAccessKeyId
  access-key-secret: yourAccessKeySecret
  bucket-name: yourBucketName
  bucket-url: yourBucketUrl
  base-path: yourBasePath
autocode:
  transfer-restart: true
  root: /home/jianghao/man/server-web
  server: /server
  server-api: /api/v1/%s
  server-initialize: /initialize
  server-model: /model/%s
  server-request: /model/%s/request/
  server-router: /router/%s
  server-service: /service/%s
  web: /web/src
  web-api: /api
  web-form: /view
  web-table: /view
aws-s3:
  bucket: xxxxx-10005608
  region: ap-shanghai
  endpoint: ""
  s3-force-path-style: false
  disable-ssl: false
  secret-id: xxxxxxxx
  secret-key: xxxxxxxx
  base-url: http://localhost:8080
  path-prefix: server
cache:
  time: 100
captcha:
  key-long: 6
  img-width: 240
  img-height: 80
casbin:
  model-path: ./rbac_model.conf
cors:
  mode: whitelist
  whitelist:
    - allow-origin: example1.com
      allow-methods: GET, POST, PUT, DELETE, PATCH
      allow-headers: content-type
      expose-headers:
        Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,
        Content-Type
      allow-credentials: true
    - allow-origin: example2.com
      allow-methods: GET, POST, PUT, DELETE
      allow-headers: content-type
      expose-headers:
        Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,
        Content-Type
      allow-credentials: true
db-list:
  - disable: false
    type: ""
    alias-name: ""
    path: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    max-idle-conns: 10
    max-open-conns: 100
    log-mode: ""
    log-zap: false
email:
  to: 760986739@qq.com
  port: 465
  from: 978561120@qq.com
  host: smtp.qq.com
  is-ssl: true
  secret: bwxrwofxhqapbahg
  nickname: "C"
excel:
  dir: uploads/excel/
hua-wei-obs:
  path: you-path
  bucket: you-bucket
  endpoint: you-endpoint
  access-key: you-access-key
  secret-key: you-secret-key
jwt:
  signing-key: 519fb1f4-4321-446a-bb7b-bfb13b68b960
  expires-time: 24 # jwt token 过期时间
  buffer-time: 60
  issuer: jianghao
local:
  path: uploads/file
mysql:
  path: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: server
  username: root
  password: "123456"
  max-idle-conns: 100
  max-open-conns: 1000
  log-mode: silent
  log-zap: true
  debug: false
pgsql:
  path: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false
qiniu:
  zone: ZoneHuadong
  bucket: "jianghaoimages"
  img-path: ""
  use-https: false
  access-key: "bLwYhR1boJaw77pjh6TOTZ4XmHwDF35SZJwInOg6"
  secret-key: "cCg2OgCmdlgTmHu40prSXDN78H8LEusNFD_vezeN"
  use-cdn-domains: false
redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""
system:
  env: develop
  addr: 3100
  db-type: mysql
  oss-type: local
  use-multipoint: false
  use-redis: true
  iplimit-count: 15000
  iplimit-time: 3600
tencent-cos:
  bucket: xxxxx-10005608
  region: ap-shanghai
  secret-id: xxxxxxxx
  secret-key: xxxxxxxx
  base-url: http://localhost:8080
  path-prefix: server
timer:
  start: false
  spec: "@monthly"
  detail:
    - tableName: sys_operation_records
      compareField: created_at
      interval: 2160h
    - tableName: jwt_blacklists
      compareField: created_at
      interval: 2160h
  tasks:
    - taskName: server1
      output: server run
      interval: 1s
zap:
  level: info
  format: console
  prefix: "[server]-"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
